# Generated by Django 6.0.4 on 2026-05-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_contactmessage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_testimonial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
