# Generated by Django 6.0.4 on 2026-05-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_contactmessage_is_testimonial_contactmessage_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
