# Generated by Django 6.0.4 on 2026-05-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
