# Generated by Django 6.0.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
